global:
  resolve_timeout: 30s
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.com'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - api_url: https://api.telegram.org
        bot_token: '7488253696:AAE2X7XKkmwnE-g7RHx12OtZd4YLimxIgis'
        chat_id: 1157305769
        parse_mode: 'HTML'
        send_resolved: true

templates:
  - '/etc/alertmanager/template/telegram.tmpl'
